---
apiVersion: v1
kind: Namespace
metadata:
  name: ingress-lab-local
  labels:
    environment: lab
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/enforce-version: latest

