---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: production-local
  namespace: production
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - app-local.127.0.0.1.sslip.io
        - api-local.127.0.0.1.sslip.io
      secretName: local-networking-tls
  rules:
    - host: app-local.127.0.0.1.sslip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: app-frontend
                port:
                  number: 80
    - host: api-local.127.0.0.1.sslip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: app-api
                port:
                  number: 8080

